### PR TITLE
Update links w/IPFS, Clean up presentation

### PR DESCRIPTION
**Pull request by guruvan**

### CODE REVIEW

**Comment by Sterling2p** [comment]
ACK

**Comment by guruvan** [comment]
@Sterling2p might be best to allow the initiator (if a committer) to complete the merge - the IPFS hash for OSX was incorrect (it's always a good idea to test the PR :) - check the links are correct & such 

Thanks :)

**Comment by Sterling2p** [comment]
Wow, I would have never checked the OSX link.  You got a lot done for this update, though.

**Comment by guruvan** [comment]
heh :) the main thing is to check that the links on the site go to the IPFS hashes listed - there was a duplicate hash in the hash list, which was the error. FYI - in the IPFS dir, I've put a README, PGP signed to verify the hashes https://ipfs.io/ipfs/QmUrNqDHQTGWMnTGEJb9EYyy7FSK5Zg6hQgqEig3qCQdBg/MAZA/MAZAchain/clients/binary-packages/v0.9-Satoshi/README

**Comment by guruvan** [comment]
We'll make this process easier & more automagic & secure/less error prone as we figure it out :)

**Pull request merged**
